# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3aa78aeb616493be3637d1c7ba066343417b58d6f2d8aeae9f22266209122a5c6ebc5f4f1c5c909beb11be000b9741df3910415382dcb0e34c8a4926ebd2107

test:
  secret_key_base: 12da5dbd1bde68603d86ab8fd31fca9e70e52c65ff862a124af0b6a61c95cafd89e5709436d5fc32998b2d6edf91939410f23f6bba71a098bdaf0e5af4c80898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
